version: '3.7'
services:
  db:
    container_name: postgres
    image: "postgres:12.0-alpine"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    container_name: foodgram
    image: "yspresi/foodgram:v3.5"
    environment:
      - DEBUG=False
    restart: always
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/static/
      - media_volume:/usr/src/app/media/
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    container_name: nginx
    image: "yspresi/foodgram_nginx:v5.11"
    volumes:
      - static_volume:/usr/src/app/static/
      - media_volume:/usr/src/app/media/
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume:
  postgres_data:
  media_volume: