# Generated by Django 3.1.1 on 2020-09-17 10:50

from django.db import migrations


import os
import csv
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent


def get_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')

    csv_file = os.path.join(BASE_DIR, 'ingredients.csv')
    data = csv.reader(open(csv_file, encoding='utf-8'), delimiter=',')
    try:
        obj_list = [
            Ingredient(
                id=id,
                name=row[0],
                dimension='г' if row[1] == '' else row[1],
            )
            for id, row in enumerate(data)
        ]
    except (IndexError):
        return 'IndexError'

    Ingredient.objects.bulk_create(obj_list)


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(get_ingredients),
    ]
